### PR TITLE
Attempt to fix #55

### LINKED ISSUE #55: Install fails when lint-staged already exists (v10.0.1)
```
yarn install v1.3.2
(node:31331) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[2/2] ⠐ eslint-config-motley
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
error /Users/.../node_modules/eslint-config-motley: Command failed.
Exit code: 1
Command: lib/postinstall.js
Arguments:
Directory: /Users/.../node_modules/eslint-config-motley
Output:
⚠️  .eslintrc.js already exists;
Make sure that it includes the following for 'eslint-config-motley'
to work as it should:

module.exports = {
  extends: 'motley',
  env: {
    browser: true,
    node: true,
    jest: true,
  }
};

⚠️  .prettierrc already exists;
Make sure that it includes the following for 'eslint-config-motley'
to work as it should:

{
  "singleQuote": true,
  "trailingComma": "all"
}
⚠️  A 'lint-staged' configuration already exists in package.json.
We won't overwrite it since it may include some of your own customizations.
We would have added the following rules, so check your configuration and modify it if needed:

{
  "*.{js,json,graphql,md,css,scss,less,ts}": [
    "prettier --write",
    "git add"
  ]
}
/Users/.../node_modules/eslint-config-motley/lib/postinstall.js:69
  return resolve();
  ^
```

### PR DESCRIPTION
**Pull request by bostrom**
Closes #55

### CODE REVIEW

**Comment by bostrom** [comment]
Seems to work now 🤞

File: lib/postinstall.js [hunk 1]
```diff
@@ -46,80 +49,76 @@ const writePrettierRc = (new Promise((resolve, reject) => {
...
   });
 }));
 
-const writeToFile = (packageJsonPath, jsonString) => fs.writeFile(packageJsonPath, jsonString, 'utf-8', (err) => {
-  if (err) {
-    return reject(err);
-  }
-
-  return resolve();
-});
```
Comment (bostrom) [inline lib/postinstall.js]: This extracted function caused trouble when being called from `writeToPackageJson`. `reject` and `resolve` aren't defined here! Moved it back inline since it's only used once there anyway.

Comment (petetnt) [reply lib/postinstall.js]: The implementation had a bug where we didn't write to file at all if `lint-staged` was specified despite other stuff missing.

The actual fuckup in #55 was that I didn't promisify the callback function (which I could have done). When this was made Node didn't have `util.promisify` at all.

**Comment by bostrom** [comment]
Yes, we could promisify those callback functions also. Would make life easier.

File: lib/postinstall.js [hunk 2]
```diff
@@ -2,12 +2,22 @@
...
 const projectPath = path.resolve(process.env.PWD, '..', '..');
+console.log('Checking configuration of ', projectPath);
 
-const writeEslintRc = (new Promise((resolve, reject) => {
+/**
+ * Writes .eslintrc.js if it doesn't exist. Warns if it exists.
+ */
+const writeEslintRc = async () => {
   const eslintPath = path.join(projectPath, '.eslintrc.js');
+  console.log(eslintPath);
```
Comment (petetnt) [inline lib/postinstall.js]: `console.log('kissa');`

File: lib/postinstall.js [hunk 3]
```diff
@@ -2,12 +2,22 @@
...
 const path = require('path');
+const { promisify } = require('util');
+
+const writeFileAsync = promisify(fs.writeFile);
+const readFileAsync = promisify(fs.readFile);
+
 // get the path to the host project.
 // process.env.PWD doesn't resolve symlinks, e.g. when developing using npm link
 const projectPath = path.resolve(process.env.PWD, '..', '..');
+console.log('Checking configuration of ', projectPath);
```
Comment (petetnt) [inline lib/postinstall.js]: `the configuration` 🤓 :neckbeard:

File: lib/postinstall.js [hunk 4]
```diff
@@ -51,78 +58,67 @@ to work as it should:
...
+  }
+
+  // Stringify package.json and write to file
+  const jsonString = JSON.stringify(packageJson, null, 2);
+
+  return writeFileAsync(packageJsonPath, jsonString, 'utf-8');
+};
 
-Promise.all([writeEslintRc, writePrettierRc, writeToPackageJson]).then(() => {
+Promise.all([writeEslintRc(), writePrettierRc(), writeToPackageJson()]).then(() => {
```
Comment (petetnt) [inline lib/postinstall.js]: Should `package.json` be done first? The others are bit moot if it doesn't exist

File: lib/postinstall.js [hunk 5]
```diff
@@ -2,12 +2,22 @@
...
 // get the path to the host project.
 // process.env.PWD doesn't resolve symlinks, e.g. when developing using npm link
 const projectPath = path.resolve(process.env.PWD, '..', '..');
+console.log('Checking configuration of ', projectPath);
 
-const writeEslintRc = (new Promise((resolve, reject) => {
+/**
+ * Writes .eslintrc.js if it doesn't exist. Warns if it exists.
+ */
+const writeEslintRc = async () => {
```
Comment (petetnt) [inline lib/postinstall.js]: Doesn't need to be async, only returns a promise

File: lib/postinstall.js [hunk 6]
```diff
@@ -25,19 +35,16 @@ to work as it should:
...
-  });
-}));
+  return writeFileAsync(eslintPath, content, 'utf-8');
+};
 
-const writePrettierRc = (new Promise((resolve, reject) => {
+/**
+ * Writes .prettierrc if it doesn't exist. Warns if it exists.
+ */
+const writePrettierRc = async () => {
```
Comment (petetnt) [inline lib/postinstall.js]: Doesn't need to be async, only returns a promise

File: lib/postinstall.js (hunk 4 above)
Comment (bostrom) [reply lib/postinstall.js]: Yes, I thought the same. Let's do it.

File: lib/postinstall.js (hunk 5 above)
Comment (bostrom) [reply lib/postinstall.js]: True, but sometimes I feel like it's a good marker to have the async keyword there to mark it as being async, even if it doesn't use await. Shouldn't do any harm.

Comment (bostrom) [reply lib/postinstall.js]: https://github.com/Microsoft/TypeScript/issues/22024#issuecomment-366548045

Comment (petetnt) [reply lib/postinstall.js]: Fine by me, it just wraps the function in a promise.

eg.

```js
async function test() {
  console.log("cat");
}

test().then(() => console.log("kissa"));
```

which might or might not be expected :)

**Comment by petetnt** [comment]
Isn't @^10 this one? :P

**Comment by bostrom** [comment]
Yes, I just realized what you meant.
